github runner initial commit to helm chart
kubefox/helm-charts pull request #2
Opened 2022-05-19 03:45 UTC by BoLB23

2022-05-19 15:08 UTC, xadhatter requested changes

2022-05-21 15:38 UTC, xadhatter commented on charts/kubefox/values.yaml
> +    enabled: false
Ignore this, just playing around with GH pull request stuff.

2022-05-21 15:44 UTC, xadhatter reviewed
Test

2022-06-01 23:55 UTC, BoLB23 commented on charts/kubefox/values.yaml
> +    enabled: false
yes - but only because helm was throwing an error for me when prometheus.prometheusOperator.enabled is not set to true or false. I figured setting enabled: false was no harm and was a quick fix without spending much time on it.

2022-06-02 14:42 UTC, xadhatter commented on charts/kubefox/values.yaml
> +    enabled: false
But shouldn't it be `true`?

2022-06-06 19:04 UTC, xadhatter approved these changes

2022-06-06 19:32 UTC, merged